name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 2.8.1
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=3.0.0<4.0.0"

dependencies:
  build: 4.0.0
  source_gen: 4.0.1
  path: 1.9.1
  glob: 2.1.3
  analyzer: ">=8.1.1 <9.0.0"
  code_builder: 4.10.1
  dart_style: 3.1.2
  injectable: 2.5.1
#      path: ../injectable
  collection: 1.19.1
  recase: 4.1.0
  meta: 1.17.0
dev_dependencies:
  build_runner: 2.8.0
  build_test: 3.4.0
  test: 1.26.3
  lints: 6.0.0
